version: '3'
services:
  db:
    image: postgres:10.0
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      PGDATA: /tmp
  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis/data
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

